#!/usr/bin/env bash
# Add a custom Nginx response header
sudo apt-get update -y
sudo apt-get install nginx -y

HOSTNAME=$(hostname)

sudo sed -i "/server_name _;/a \\\n location / {\n add_header X-Served-By $HOSTNAME;\n }\n" /etc/nginx/sites-available/default

sudo service nginx restart
