#!/usr/bin/env bash
# Add a custom Nginx response header
sudo apt-get update -y
sudo apt-get install nginx -y

HOSTNAME=$(hostname)

sudo sed -i "server_name _;\a \\ location / {\n add_header X-Served-By $HOSTNAME;\n }" /etc/nginx/sites-available/default

sudo service nginx restart
