#!/usr/bin/env bash
# Installs and configure HAProxy on Ubuntu server

sudo apt-get update
sudo apt-get install -y haproxy

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 3.84.161.130:80 check
    server web-02 54.167.150.211:80 check
EOF


sudo service haproxy restart

echo "HAProxy configured with backend servers:"
echo "web-01"
echo "web-02"
