#!/usr/bin/env bash
# Install nginx to listen on port 80
sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sevice nginx start

sudo sed -i 's/listen 80 478586-web-01;/listen 80;/g' /etc/nginx/sites-available/default

sudo service nginx restart

echo "Nginx has been installed"
