#!/usr/bin/env bash
#This script displays listening ports, PID, name of the prgram to which each socket belongs
if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi
netstat -l
