#!/usr/bin/env bash
# This script pings an ip address passed as an argument
network_ip=$*
if [ -z "$*" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else 
	ping -c 5 "$network_ip"
fi
