#!/usr/bin/env bash
#This script displays the time for 12 hours and 59 minutes
counter1=0
while [ $counter1 -le 12 ]; do
	counter2=1
	echo "Hour: $counter1"
	while [ $counter2 -lt 60 ]; do
		echo $counter2
	((counter2++))
	done
	((counter1++))
done
