#!/usr/bin/env bash
# This script configures an Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i 's/^127\.0\.0\.1\s\+localhost/127.0.0.2 localhost/g' ~/hosts.new
sed -i '1a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
