#!/usr/bin/bash
# This script displays all active IPv4 IPs on the machine it's executed on
#ip_address=$(ip addr show | grep -oP '(?<=inet )[\d.]+(?=/\d+)')
#for i in $ip_address; do
   # echo "$i"
#done
ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1
