#!/usr/bin/env bash
# Ensure nginx runs as nginx user and nginx must be listening on
# port all active IPs on port 8080

sed i 's/user .*;/user nginx;/g' /etc/nginx/nginx.conf
sed i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sed i 's/listen \[::\]:80 default_server;/listen [::]:8080 default_server;/g' /etc/nginx/sites-available/default

chown -R nginx:nginx /var/www/html

systemctl restart nginx
